spring:
  profiles:
    active: release

  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        jdbc: debug

---

spring:
  config:
    activate:
      on-profile: release

  datasource:
    url: jdbc:mysql://localhost:3306/baemin
    username: root
    password: 5643

---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MySQL;
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql